# Simple Docker Compose File to Run the Storefront Application
version: "0.0.0-dev"

services:

  # The container representing the Main Node.JS Application
  # web_application:
  #   build: ./
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   environment:
  #     - DEPLOYMENT=docker-compose
  #   healthcheck:
  #     test: "curl -H 'Accept: application/json' -X GET 'http://localhost/api/healthcheck'"
  #     interval: 15s
  #     timeout: 5s
  #     start_period: 15s

  # One-off container used to tie together the main MongoDB instance with it's corresponding replication sets (once all three services pass the health checks).
  # This container is to be disregarded once the replication sets are tied together (hence the no-restart policy).
  dbreplsetup:
    image: "mongo:latest"
    restart: no
    depends_on:
      database:
        condition: service_healthy
      dbreplset01:
        condition: service_healthy
      dbreplset02:
        condition: service_healthy
    entrypoint: >
      mongosh database:27017/admin --quiet --eval
      '
        rs.initiate();
        rs.add({ host: "host.docker.internal:27018", priority: 0, votes: 0 });
        rs.add({ host: "host.docker.internal:27019", priority: 0, votes: 0 });
      '

  # The container representing the database for the application.
  database:
    image: "mongo:latest"
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: mongod --bind_ip 0.0.0.0 --replSet rs0
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin --quiet
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

  # The container representing the first replication set.
  dbreplset01:
    image: "mongo:latest"
    restart: unless-stopped
    command: mongod --replSet rs0 --bind_ip 0.0.0.0 --port 27018
    ports:
      - "27018:27018"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27018/admin --quiet
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"

  # The container representing the second replication set.
  dbreplset02:
    image: "mongo:latest"
    restart: unless-stopped
    command: mongod --replSet rs0 --bind_ip 0.0.0.0 --port 27019
    ports:
      - "27019:27019"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27019/admin --quiet
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5
    volumes:
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:
