name: Build Docker Image and Push to Docker Hub

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to the Docker CLI
        run: docker login -u samuelcmace -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create Tag for Docker
        id: create_tag
        run: echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.io/samuelcmace/nodejs-store:${{ steps.create_tag.outputs.tag }}

      - name: Push the Image to Docker Hub
        run: docker push docker.io/samuelcmace/nodejs-store:${{ steps.create_tag.outputs.tag }}
